services:

  anometras:
    container_name: anometras
    build:
      context: .
    ports:
      - "8000:8000"    


  postgres:
    container_name: pg_anometras
    image: pgvector/pgvector:pg17 
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/pgvector/data:/var/lib/postgresql/data
      - ./provisioning/init_pgvector.sql:/docker-entrypoint-initdb.d/init_pgvector.sql
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb

  pg_grafana:
    container_name: pg_grafana
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: my_grafana_db
      POSTGRES_USER: my_grafana_user
      POSTGRES_PASSWORD: my_grafana_pwd
    ports:
      - "5499:5432"
    volumes:
      - ./volumes/pg_grafana:/var/lib/postgresql/data

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    user: "0:0"
    environment:
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: pg_grafana:5432
      GF_DATABASE_NAME: my_grafana_db
      GF_DATABASE_USER: my_grafana_user
      GF_DATABASE_PASSWORD: my_grafana_pwd
      GF_DATABASE_SSL_MODE: disable
    restart: unless-stopped
    depends_on:
        - pg_grafana
    ports:
      - 3111:3000
    volumes:
      - ./volumes/grafana_data:/var/lib/grafana


