{
 "title": "Anometro apžvalga",
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  { "title": "Bendras", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Akumuliuotų h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "with data as (\n  select\n    date_trunc('week', annotation_upload_date) as time,\n    sum(annot_time_slot_duration) as value\n  from elan_annot\n  group by 1\n)\n\nselect time,\n  -- value,  \n  sum(value) over (order by time asc rows between unbounded preceding and current row)/3600000 \n from data;\n\n"
    }
   ]
  },
  {
   "title": "Iki tikslo",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(annot_time_slot_duration)/3600000 FROM elan_annot "
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Anotacijų, h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT \n$__timeGroupAlias(annotation_upload_date,1d),\nsum(annot_time_slot_duration)/3600000 AS \"val\" \nFROM elan_annot \nWHERE\n  $__timeFilter(annotation_upload_date)\nGROUP BY 1 \nORDER BY 1 \n"
    }
   ]
  },
  {
   "title": "Failų įkėlimas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "\nSELECT\n  $__timeGroupAlias(annotation_upload_date,1d),\n  count(file_id) AS \"failai\"\nFROM elan_file\nWHERE\n  $__timeFilter(annotation_upload_date)\nGROUP BY 1\nORDER BY 1\n"
    }
   ]
  }
 ]
}